/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/households": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Household */
        post: operations["create_household_api_households_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Household */
        post: operations["join_household_api_households_join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Session */
        get: operations["get_current_session_api_session_get"];
        put?: never;
        post?: never;
        /** Delete Current Session */
        delete: operations["delete_current_session_api_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/invite/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate Invite */
        post: operations["rotate_invite_api_households_invite_rotate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/members/{member_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable Member */
        post: operations["disable_member_api_households_members__member_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/members/{member_id}/pin/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Member Pin */
        post: operations["reset_member_pin_api_households_members__member_id__pin_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dishes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dishes */
        get: operations["get_dishes_api_dishes_get"];
        put?: never;
        /** Post Dish */
        post: operations["post_dish_api_dishes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dishes/{dish_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dish */
        get: operations["get_dish_api_dishes__dish_id__get"];
        put?: never;
        post?: never;
        /** Delete Dish */
        delete: operations["delete_dish_api_dishes__dish_id__delete"];
        options?: never;
        head?: never;
        /** Patch Dish */
        patch: operations["patch_dish_api_dishes__dish_id__patch"];
        trace?: never;
    };
    "/api/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingredients */
        get: operations["get_ingredients_api_ingredients_get"];
        put?: never;
        /** Post Ingredient */
        post: operations["post_ingredient_api_ingredients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meal-slots/{local_date}/{meal_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meal Slot */
        get: operations["get_meal_slot_api_meal_slots__local_date___meal_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meal-slots/{slot_id}/requests/{dish_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Meal Request */
        put: operations["put_meal_request_api_meal_slots__slot_id__requests__dish_id__put"];
        post?: never;
        /** Delete Meal Request */
        delete: operations["delete_meal_request_api_meal_slots__slot_id__requests__dish_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meal-slots/{slot_id}/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Meal Menu */
        put: operations["put_meal_menu_api_meal_slots__slot_id__menu_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendations/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Search */
        post: operations["post_search_api_recommendations_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendations/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Random */
        post: operations["post_random_api_recommendations_random_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Event */
        post: operations["create_event_api_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validation-checkins/{week_start}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Validation Checkin */
        put: operations["put_validation_checkin_api_validation_checkins__week_start__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics Summary */
        get: operations["get_metrics_summary_api_metrics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthResponse */
        AuthResponse: {
            household: components["schemas"]["HouseholdSummary"];
            member: components["schemas"]["MemberSummary"];
        };
        /** ConfirmationDetail */
        ConfirmationDetail: {
            /**
             * Meal Slot Id
             * Format: uuid
             */
            meal_slot_id: string;
            /** Local Date */
            local_date?: string | null;
            /** Meal Type */
            meal_type?: ("lunch" | "dinner") | null;
            /** Request Count */
            request_count?: number | null;
            /** Participant Count */
            participant_count?: number | null;
            /** Confirmation Seconds */
            confirmation_seconds?: number | null;
        };
        /** CookSummary */
        CookSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nickname */
            nickname: string;
        };
        /** CreateHouseholdRequest */
        CreateHouseholdRequest: {
            /** Household Name */
            household_name: string;
            /** Owner Name */
            owner_name: string;
            /** Pin */
            pin: string;
            /** Timezone */
            timezone: string;
        };
        /** CreateHouseholdResponse */
        CreateHouseholdResponse: {
            household: components["schemas"]["HouseholdSummary"];
            member: components["schemas"]["MemberSummary"];
            /** Invite Code */
            invite_code: string;
        };
        /** DecisionSourceCounts */
        DecisionSourceCounts: {
            /**
             * Direct
             * @default 0
             */
            direct: number;
            /**
             * Random
             * @default 0
             */
            random: number;
            /**
             * Ingredient
             * @default 0
             */
            ingredient: number;
        };
        /** DishCreate */
        DishCreate: {
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "荤菜" | "素菜" | "主食" | "汤" | "其他";
            /** Cook Ids */
            cook_ids: string[];
            /** Ingredients */
            ingredients: string[];
            /** Image Key */
            image_key?: string | null;
        };
        /** DishRead */
        DishRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "荤菜" | "素菜" | "主食" | "汤" | "其他";
            /** Cooks */
            cooks: components["schemas"]["CookSummary"][];
            /** Ingredients */
            ingredients: components["schemas"]["IngredientSummary"][];
            /** Image Url */
            image_url: string | null;
            /** Archived At */
            archived_at: string | null;
            updated_by: components["schemas"]["UpdatedBySummary"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DishUpdate */
        DishUpdate: {
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "荤菜" | "素菜" | "主食" | "汤" | "其他";
            /** Cook Ids */
            cook_ids: string[];
            /** Ingredients */
            ingredients: string[];
            /** Image Key */
            image_key?: string | null;
        };
        /** EventCreate */
        EventCreate: {
            /**
             * Name
             * @enum {string}
             */
            name: "meal_opened" | "first_request_added" | "menu_confirmed" | "menu_modified";
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
        };
        /** EventRead */
        EventRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Name
             * @enum {string}
             */
            name: "meal_opened" | "first_request_added" | "menu_confirmed" | "menu_modified";
            /** Properties */
            properties: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryEntry */
        HistoryEntry: {
            /**
             * Meal Slot Id
             * Format: uuid
             */
            meal_slot_id: string;
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /**
             * Meal Type
             * @enum {string}
             */
            meal_type: "lunch" | "dinner";
            /** Menu */
            menu: components["schemas"]["HistoryMenuItem"][];
            last_modified_by: components["schemas"]["HistoryLastModifier"] | null;
            /** Last Modified At */
            last_modified_at: string | null;
        };
        /** HistoryLastModifier */
        HistoryLastModifier: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nickname */
            nickname: string;
        };
        /** HistoryMenuItem */
        HistoryMenuItem: {
            /**
             * Dish Id
             * Format: uuid
             */
            dish_id: string;
            /** Dish Name */
            dish_name: string;
            /** Image Key */
            image_key: string | null;
        };
        /** HouseholdSummary */
        HouseholdSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
        };
        /** IngredientCreate */
        IngredientCreate: {
            /** Name */
            name: string;
            /** Aliases */
            aliases?: string[];
        };
        /** IngredientRead */
        IngredientRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Aliases */
            aliases: string[];
        };
        /** IngredientSummary */
        IngredientSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** JoinHouseholdRequest */
        JoinHouseholdRequest: {
            /** Invite Code */
            invite_code: string;
            /** Nickname */
            nickname: string;
            /** Pin */
            pin: string;
        };
        /** LastModifierSummary */
        LastModifierSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nickname */
            nickname: string;
        };
        /** MealSlotRead */
        MealSlotRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /**
             * Meal Type
             * @enum {string}
             */
            meal_type: "lunch" | "dinner";
            /**
             * Status
             * @enum {string}
             */
            status: "not_started" | "pending" | "confirmed";
            /** Version */
            version: number;
            /** Requests */
            requests: components["schemas"]["MergedMealRequestRead"][];
            /** Menu */
            menu: components["schemas"]["MenuItemRead"][];
            last_modified_by: components["schemas"]["LastModifierSummary"] | null;
            /** Last Modified At */
            last_modified_at: string | null;
        };
        /** MemberSummary */
        MemberSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nickname */
            nickname: string;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "member";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "disabled";
        };
        /** MenuItemRead */
        MenuItemRead: {
            /**
             * Dish Id
             * Format: uuid
             */
            dish_id: string;
            /** Dish Name */
            dish_name: string;
            /** Image Key */
            image_key: string | null;
        };
        /** MenuUpdate */
        MenuUpdate: {
            /** Dish Ids */
            dish_ids?: string[];
            /** Expected Version */
            expected_version: number;
        };
        /** MergedMealRequestRead */
        MergedMealRequestRead: {
            /**
             * Dish Id
             * Format: uuid
             */
            dish_id: string;
            /** Dish Name */
            dish_name: string;
            /** Image Key */
            image_key: string | null;
            /** Requested By */
            requested_by: components["schemas"]["RequestedBySummary"][];
        };
        /** MetricsSummary */
        MetricsSummary: {
            /** Median Confirmation Seconds */
            median_confirmation_seconds: number | null;
            /** App Decided Meal Ratio */
            app_decided_meal_ratio: number | null;
            decision_source_counts: components["schemas"]["DecisionSourceCounts"];
            /** Menu Modified Count */
            menu_modified_count: number;
            /** Confirmation Details */
            confirmation_details: components["schemas"]["ConfirmationDetail"][];
            /** Offline Discussion Count */
            offline_discussion_count?: number | null;
        };
        /** RandomRequest */
        RandomRequest: {
            /** Cook Ids */
            cook_ids?: string[];
            /** Categories */
            categories?: ("荤菜" | "素菜" | "主食" | "汤" | "其他")[];
            /** Available Ingredient Ids */
            available_ingredient_ids?: string[];
            /** Meal Slot Id */
            meal_slot_id?: string | null;
            /** Seed */
            seed?: number | null;
        };
        /** RandomResponse */
        RandomResponse: {
            dish: components["schemas"]["RecommendedDishRead"];
            /** Meal Slot Id */
            meal_slot_id: string | null;
        };
        /** RecommendationFilters */
        RecommendationFilters: {
            /** Cook Ids */
            cook_ids?: string[];
            /** Categories */
            categories?: ("荤菜" | "素菜" | "主食" | "汤" | "其他")[];
            /** Available Ingredient Ids */
            available_ingredient_ids?: string[];
            /** Meal Slot Id */
            meal_slot_id?: string | null;
        };
        /** RecommendedDishRead */
        RecommendedDishRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "荤菜" | "素菜" | "主食" | "汤" | "其他";
            /** Cooks */
            cooks: components["schemas"]["CookSummary"][];
            /** Ingredients */
            ingredients: components["schemas"]["IngredientSummary"][];
            /** Missing Ingredients */
            missing_ingredients: components["schemas"]["IngredientSummary"][];
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "ready" | "one_missing";
            /** Last Eaten On */
            last_eaten_on: string | null;
            /** Weight */
            weight: string;
        };
        /** RequestedBySummary */
        RequestedBySummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nickname */
            nickname: string;
        };
        /** ResetPinRequest */
        ResetPinRequest: {
            /** Pin */
            pin: string;
        };
        /** RotateInviteResponse */
        RotateInviteResponse: {
            /** Invite Code */
            invite_code: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Ready */
            ready: components["schemas"]["RecommendedDishRead"][];
            /** One Missing */
            one_missing: components["schemas"]["RecommendedDishRead"][];
            /** Meal Slot Id */
            meal_slot_id: string | null;
        };
        /** SessionResponse */
        SessionResponse: {
            household: components["schemas"]["HouseholdSummary"];
            member: components["schemas"]["MemberSummary"];
            /** Members */
            members: components["schemas"]["MemberSummary"][];
        };
        /** UpdatedBySummary */
        UpdatedBySummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nickname */
            nickname: string;
        };
        /** ValidationCheckinRead */
        ValidationCheckinRead: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Home Meal Count */
            home_meal_count: number;
            /** Offline Discussion Count */
            offline_discussion_count: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationCheckinWrite */
        ValidationCheckinWrite: {
            /** Home Meal Count */
            home_meal_count: number;
            /** Offline Discussion Count */
            offline_discussion_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_household_api_households_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHouseholdRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateHouseholdResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_household_api_households_join_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinHouseholdRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_session_api_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    delete_current_session_api_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rotate_invite_api_households_invite_rotate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotateInviteResponse"];
                };
            };
        };
    };
    disable_member_api_households_members__member_id__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_member_pin_api_households_members__member_id__pin_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dishes_api_dishes_get: {
        parameters: {
            query?: {
                cook_id?: string | null;
                category?: string | null;
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_dish_api_dishes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DishCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dish_api_dishes__dish_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dish_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dish_api_dishes__dish_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dish_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_dish_api_dishes__dish_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dish_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DishUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingredients_api_ingredients_get: {
        parameters: {
            query?: {
                query?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_ingredient_api_ingredients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meal_slot_api_meal_slots__local_date___meal_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                local_date: string;
                meal_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealSlotRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_meal_request_api_meal_slots__slot_id__requests__dish_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
                dish_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealSlotRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meal_request_api_meal_slots__slot_id__requests__dish_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
                dish_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_meal_menu_api_meal_slots__slot_id__menu_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealSlotRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_search_api_recommendations_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationFilters"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_random_api_recommendations_random_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RandomRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RandomResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event_api_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_validation_checkin_api_validation_checkins__week_start__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                week_start: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidationCheckinWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationCheckinRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_api_history_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_summary_api_metrics_summary_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
