/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/households": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Household */
        post: operations["create_household_api_households_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Household */
        post: operations["join_household_api_households_join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Session */
        get: operations["get_current_session_api_session_get"];
        put?: never;
        post?: never;
        /** Delete Current Session */
        delete: operations["delete_current_session_api_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/invite/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate Invite */
        post: operations["rotate_invite_api_households_invite_rotate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/members/{member_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable Member */
        post: operations["disable_member_api_households_members__member_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/households/members/{member_id}/pin/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Member Pin */
        post: operations["reset_member_pin_api_households_members__member_id__pin_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dishes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dishes */
        get: operations["get_dishes_api_dishes_get"];
        put?: never;
        /** Post Dish */
        post: operations["post_dish_api_dishes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dishes/{dish_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dish */
        get: operations["get_dish_api_dishes__dish_id__get"];
        put?: never;
        post?: never;
        /** Delete Dish */
        delete: operations["delete_dish_api_dishes__dish_id__delete"];
        options?: never;
        head?: never;
        /** Patch Dish */
        patch: operations["patch_dish_api_dishes__dish_id__patch"];
        trace?: never;
    };
    "/api/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingredients */
        get: operations["get_ingredients_api_ingredients_get"];
        put?: never;
        /** Post Ingredient */
        post: operations["post_ingredient_api_ingredients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthResponse */
        AuthResponse: {
            household: components["schemas"]["HouseholdSummary"];
            member: components["schemas"]["MemberSummary"];
        };
        /** CookSummary */
        CookSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nickname */
            nickname: string;
        };
        /** CreateHouseholdRequest */
        CreateHouseholdRequest: {
            /** Household Name */
            household_name: string;
            /** Owner Name */
            owner_name: string;
            /** Pin */
            pin: string;
            /** Timezone */
            timezone: string;
        };
        /** CreateHouseholdResponse */
        CreateHouseholdResponse: {
            household: components["schemas"]["HouseholdSummary"];
            member: components["schemas"]["MemberSummary"];
            /** Invite Code */
            invite_code: string;
        };
        /** DishCreate */
        DishCreate: {
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "荤菜" | "素菜" | "主食" | "汤" | "其他";
            /** Cook Ids */
            cook_ids: string[];
            /** Ingredients */
            ingredients: string[];
            /** Image Key */
            image_key?: string | null;
        };
        /** DishRead */
        DishRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "荤菜" | "素菜" | "主食" | "汤" | "其他";
            /** Cooks */
            cooks: components["schemas"]["CookSummary"][];
            /** Ingredients */
            ingredients: components["schemas"]["IngredientSummary"][];
            /** Image Url */
            image_url: string | null;
            /** Archived At */
            archived_at: string | null;
            updated_by: components["schemas"]["UpdatedBySummary"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DishUpdate */
        DishUpdate: {
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "荤菜" | "素菜" | "主食" | "汤" | "其他";
            /** Cook Ids */
            cook_ids: string[];
            /** Ingredients */
            ingredients: string[];
            /** Image Key */
            image_key?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HouseholdSummary */
        HouseholdSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
        };
        /** IngredientCreate */
        IngredientCreate: {
            /** Name */
            name: string;
            /** Aliases */
            aliases?: string[];
        };
        /** IngredientRead */
        IngredientRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Aliases */
            aliases: string[];
        };
        /** IngredientSummary */
        IngredientSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** JoinHouseholdRequest */
        JoinHouseholdRequest: {
            /** Invite Code */
            invite_code: string;
            /** Nickname */
            nickname: string;
            /** Pin */
            pin: string;
        };
        /** MemberSummary */
        MemberSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nickname */
            nickname: string;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "member";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "disabled";
        };
        /** ResetPinRequest */
        ResetPinRequest: {
            /** Pin */
            pin: string;
        };
        /** RotateInviteResponse */
        RotateInviteResponse: {
            /** Invite Code */
            invite_code: string;
        };
        /** SessionResponse */
        SessionResponse: {
            household: components["schemas"]["HouseholdSummary"];
            member: components["schemas"]["MemberSummary"];
            /** Members */
            members: components["schemas"]["MemberSummary"][];
        };
        /** UpdatedBySummary */
        UpdatedBySummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nickname */
            nickname: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_household_api_households_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHouseholdRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateHouseholdResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_household_api_households_join_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinHouseholdRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_session_api_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    delete_current_session_api_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rotate_invite_api_households_invite_rotate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotateInviteResponse"];
                };
            };
        };
    };
    disable_member_api_households_members__member_id__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_member_pin_api_households_members__member_id__pin_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dishes_api_dishes_get: {
        parameters: {
            query?: {
                cook_id?: string | null;
                category?: string | null;
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_dish_api_dishes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DishCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dish_api_dishes__dish_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dish_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dish_api_dishes__dish_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dish_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_dish_api_dishes__dish_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dish_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DishUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DishRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingredients_api_ingredients_get: {
        parameters: {
            query?: {
                query?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_ingredient_api_ingredients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
